### ISSUE TITLE
t2d abastotal: doesn't download dependencies

### ISSUE THREAD

**Issue by glizek** [Vauxoo/travis2docker#100]
When I created a t2d of abastotal, it didn't download any of the dependencies.

![abastotal2](https://cloud.githubusercontent.com/assets/25072045/25399215/4b8f6242-29b4-11e7-87c8-28040a35ff2e.png)

**Comment by luistorresm** [comment]
@glizek 

In what folder you run .10 & .20? 1 or 2?

Regards

**Comment by glizek** [comment]
@luistorresm 
I'm running it in folder 2

**Comment by moylop260** [comment]
Did you have the full log output from 10-build command?

**Comment by luistorresm** [comment]
You must run folder 1

https://github.com/Vauxoo/abastotal/blob/10.0/.travis.yml#L34

Folder 2 only check lint errors, and 1 run all instance.

Could you close this Issue?

Regards

**Comment by glizek** [comment]
@luistorresm 

 thank you.
