### ISSUE TITLE
Docker alpine / Toolchains

### ISSUE THREAD

**Issue by roscopecoltran** [Vauxoo/travis2docker#103]
HI guys,

Hope u are all well !

Just wanted to ask how complicated it would be to choose between a docker alpine based image with travis; it would be awesome to shrink the size of the running containers ^^.

**refs:**
- Alpine + Travis:
  - https://github.com/jamespamplin/docker-alpine-travis-cli
  - https://github.com/caktux/docker-travis-cli
  - https://github.com/alpinelinux/alpine-chroot-install

I would see only a constraint for mapping the runtime packages and map packages from apt to apk. Maybe you have a wider scope of issues to share with me for anticipate the task load.

As I am thinking to use also some additional toolchains, it would be awesome to select the docker base image.

**Misc:**
- Ubuntu + Travis + Toolchains 
  - https://github.com/hunter-packages/travis-linux-docker
- Docker + Toolchains
  - https://github.com/dockcross/dockcross

Have an awesome day !

Cheers,
Richard

**Comment by moylop260** [comment]
Hello
Thanks for issue.

You can use other image using
--docker-image --docker-user parameter.

Travis has available a lot inages to use but are very heavy.
Use a custom ligth image is a good idea.
Do you have created a custom image?

**Comment by roscopecoltran** [comment]
Not yet, I just found your package yesterday as I am working on some kind of helper, in python, to help me to ci and build cross-platform packages. But to will definitely do it ! :-)

Would be cool to have some embedded registry to save all the travis.yaml file processed with a graph linking them to the vcs project uri. :-)

**Comment by luisg123v** [comment]
This repo will be deprecated soon, so closing.
