### ISSUE TITLE
odoo user do not see an already installed python package and can not install new packages

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/travis2docker#104]
Here is a video showing the error
https://youtu.be/52NRy5REWWQ

**Comment by zaoral** [comment]
HI @JesusZapata 

I am not sure if this is the correct repository where the issue should belong.
Please let me know the correct repository in order to move the issue there.

Best Regards

**Comment by JesusZapata** [comment]
@zaoral 
If you want to install a package in a container you can enter the container as root
`docker exec --user=root -it CONTAINER_ID bash`

This is what you ask?

**Comment by JesusZapata** [comment]
@zaoral 
You could give me the original t2d command to replicate the error

**Comment by moylop260** [comment]
Could you share us the `docker images | grep shippable` result in order to see the sha version too, please?

**Comment by zaoral** [comment]
Hi @JesusZapata @moylop260 

1. yes, if I exec the containter as root user, I am not able to install libxml2-python. And neither I am able to run my script: it said the same that the argcomplete is not installed when I try to run the script, but when I ran pip freeze | grep argcomplete. it saids is installed 'argcomplete==1.8.2'. Even with root user I am not able to run the script because of "missing" dependencies. 
2. there is not special step to replicate the command. only create and run a t2d container using t2d git@ssh-path.git, and then runing the 10.0-build and 20.0-run. The contaier that throwme this error was created from the forecast repository.
3. the sha version I am using is  e95c9a55a10b,  of date 2017-04-13 12:50:16 -0400 VET

**Comment by zaoral** [comment]
Hi @JesusZapata

Any news about this issue?

**Comment by JesusZapata** [comment]
@zaoral 

**About argcomplete**
I made this PR https://github.com/vauxoo-dev/gist-vauxoo/pull/95 for auto install of `argcomplete` 

![image](https://cloud.githubusercontent.com/assets/1387970/26701588/b5adafa0-46ef-11e7-9fe1-1e789a67b92c.png)

**About libxml2**
I run `docker exec --user=root -it **SHA_DOCKER** bash` and install `python-libxml2` with this command `sudo apt-get install python-libxml2`

![image](https://cloud.githubusercontent.com/assets/1387970/26702316/7f955514-46f2-11e7-8e9c-33b113048a0d.png)

And the command python csv2xml.py now no show error

![image](https://cloud.githubusercontent.com/assets/1387970/26702392/c774cde2-46f2-11e7-92ea-c85c5adf35ee.png)

**Comment by JesusZapata** [comment]
@zaoral 
I test this changes with this command `t2d git@github.com:JesusZapata/asdcust.git 10.0`
Only if you want to try

**Comment by zaoral** [comment]
Test it, everything is working properly.
Thank you @JesusZapata

**Comment by JesusZapata** [comment]
@zaoral 
If you can test everything, you can close this issue and this PR https://github.com/vauxoo-dev/gist-vauxoo/pull/95 ? 
Or do you have another problem?
