### ISSUE TITLE
Question about build_image travis param

### ISSUE THREAD

**Issue by GSLabIt** [Vauxoo/travis2docker#156]
hi there, 

is `build_image` in  `.travis.yml `used to pull the correct image? 

It seems should be used as per:
https://github.com/Vauxoo/travis2docker/blob/74ba078425b42f454b8510dd0cb6eac1347e6963/src/travis2docker/cli.py#L87

but actually it get the image set in repository configuration:

<img width="1243" alt="Schermata 2022-09-19 alle 17 22 28" src="https://user-images.githubusercontent.com/11652845/191053716-a6d956e4-2777-44fd-912b-bcd4098acd50.png">

any hint on how to set image name from `.travis.yml`?

**Comment by moylop260** [comment]
Hi @GSLabIt 

It is using the configured in the runbot.repo record

**Comment by GSLabIt** [comment]
> Hi @GSLabIt
> 
> It is using the configured in the runbot.repo record

Oh ok, thanks
