### ISSUE TITLE
deployv: Allow autocomplete the python debugger "pdb" in vim.

### ISSUE THREAD

**Issue by ysantiago** [Vauxoo/travis2docker#162]
Python debugger with ```pdb``` in vim is frequently used, therefore it is quite useful to turn on autocomplete when typing pdb + tab to  get ```__import__('pdb').set_trace()```.

**Comment by luisg123v** [comment]
AFAIK it should be:

`import pdb; pdb.set_trace()`

So it's easily catched by lints if someone forgets to remove it.

**Comment by moylop260** [comment]
Superseded by https://github.com/Vauxoo/travis2docker/issues/165
