### ISSUE TITLE
t2d --deployv: Configure VIM only if you have defined a build-arg to do it

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/travis2docker#165]
Continue of https://github.com/Vauxoo/travis2docker/issues/164 but for VIM custom installation

MQT was installing a custom VIM and it was working
 - https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/scripts/build-image.sh#L246-L343

We need to migrate the vim installation to new method to t2d:
 - https://github.com/Vauxoo/travis2docker/blob/c27cd5fbac5624db2b5a5d7d01b10f5124b37f95/src/travis2docker/templates/build.sh

But not all the devs are using VIM

There are other devs using VSCode or other IDEs

So, It could be great using the same behaviour than issue 164 related to only install this VIM + theme + configuration if a environment variable is defined and it is assigned from build-arg

Something lile `VIM_INSTALL`

**Comment by luistorresm** [comment]
Hello @antonag32 

Do you have any news about this ticket?

Or maybe an expected date?

Regards

**Comment by antonag32** [comment]
@luistorresm 

Hello, I think I will make a PR for it today.

**Comment by moylop260** [comment]
@antonag32 

Be aware about the last review, please
 - https://github.com/Vauxoo/travis2docker/pull/176#pullrequestreview-1144335454

Could you send a video with your local functional testing, please?

**Comment by antonag32** [comment]
Yes, working on it

**Comment by moylop260** [comment]
@hbto @luistorresm @deivislaya @ysantiago 

Could you test the new feature using?
 - `t2d --deployv --build-env-args=VIM_INSTALL REPO BRANCH`

You even can use the `alias` to set it next times

Notice you need to update the t2d pypi package to `v6.4.1`

Before to build you can double confirm checking the Dockerfile output:

You should see the following output:
 - `cat .t2d/script/git_git.vauxoo.com_vauxoo_sbd.git/14.0/3_6/env_1_job_1/Dockerfile |grep VIM`

`ENV VIM_INSTALL=TRUE`

It means, it is already configured and the vim plugins will be installed

I just tested and use the word "pdb" + tab and it was auto-filled
 - ![vim](https://user-images.githubusercontent.com/6644187/196850695-a1bf4913-a6e9-4d55-acc9-bf3fd3cdfe42.gif)


@antonag32 

It is showing errors on install and warning opening python files

But it good for now

I will let it the issue opened in order to review it after

**Comment by luistorresm** [comment]
Hello @moylop260 

I get this error when found a lint error:
![Captura de Pantalla 2022-10-20 a la(s) 12 26 51](https://user-images.githubusercontent.com/7606656/197017734-ec00cf02-3d78-476e-ac98-030eb15b7e17.png)

**Comment by moylop260** [comment]
@antonag32 

Could you complement the t2d output message with:
 - `vim spf13 is not configured, if you want it run t2d --...`

**Comment by moylop260** [comment]
@antonag32 

Could you fix the following error, please?

```bash
[✔] Successfully cloned vundle.
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
[✔] Now updating/installing plugins using Vundle

Thanks for installing spf13-vim.
© 2022 http://vim.spf13.com/
Cloning https://github.com/vauxoo/vim-openerp.git ...
Cloning https://github.com/davidhalter/jedi-vim.git ...
error: unknown switch `d'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive[=<pathspec>]
                          initialize submodules in the clone
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root

/bin/sh: 230: cd: can't cd to /home/odoo/.vim/bundle/YouCompleteMe
Cloning https://github.com/wakatime/vim-wakatime.git ...
ZSH_INSTALL is not defined. Skipping zsh installation.
Removing intermediate container 38a6fef5da55
 ---> d5e50af59c52
Step 19/21 : USER odoo
```

**Comment by moylop260** [comment]
@antonag32 

Is possible to fix the following one too, please?
```bash
[odoo@e1f6a53af9ef]~/instance/extra_addons/account-customer-invoice-split-discount/account_customer_invoice_split_discount/models$
 (14.0)$ vim account_move.py
Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
Press ENTER or type command to continue
```

**Comment by moylop260** [comment]
@hbto 

The pylint was fixed:
 - <img width="1084" alt="Screen Shot 2022-10-21 at 14 23 36" src="https://user-images.githubusercontent.com/6644187/197273859-b120b0b8-8cef-4d35-80e0-146be22e4085.png">


Note: You will need to update the t2d package

**Comment by hbto** [comment]
> @hbto
> 
> The pylint was fixed:
> 
>     * <img alt="Screen Shot 2022-10-21 at 14 23 36" width="1084" src="https://user-images.githubusercontent.com/6644187/197273859-b120b0b8-8cef-4d35-80e0-146be22e4085.png">
> 
> 
> Note: You will need to update the t2d package

Thanks a lot I will check in my next cycle of t2d generation.

Regards.

**Comment by antonag32** [comment]
@moylop260 the requested fixes are here:
https://github.com/Vauxoo/travis2docker/pull/183

**Comment by moylop260** [comment]
@antonag32 

I don't know if something is wrong with this plugin or the version but opening a .py file it is raising the following errors and request press enter again and again:
 - <img width="891" alt="Screenshot 2022-10-26 at 10 28 43" src="https://user-images.githubusercontent.com/6644187/198069104-a827da92-f406-4b45-a42c-34f5a062c29b.png">


Could you check it, please?

**Comment by moylop260** [comment]
For record,

The installation process was fixed:
 - <img width="866" alt="Screenshot 2022-10-26 at 10 29 51" src="https://user-images.githubusercontent.com/6644187/198069363-a9285f0d-35db-4f93-a704-3994513bdf56.png">

Thank you!

**Comment by hbto** [comment]
> 



> @antonag32
> 
> Could you complement the t2d output message if VIM_INSTALL was not defined with:
> 
>     * `vim spf13 is not configured, if you want it run t2d --build-env-args=VIM_INSTALL`

<img width="1352" alt="Screen Shot 2022-10-26 at 22 52 13" src="https://user-images.githubusercontent.com/7598010/198188290-a8e26df1-844e-4ceb-80cc-6c7c7c584598.png">

There is a typo in the output.

Regards.

**Comment by moylop260** [comment]
Done from https://github.com/Vauxoo/travis2docker/pull/185

IMHO this issue is ready

Let me know if not

For now, closing it
