### ISSUE TITLE
Add spf13 vim plugins

### ISSUE THREAD

**Issue by hbto** [Vauxoo/travis2docker#179]
Hello.

Could it be possible to add the spf13 vim plugins to the development image.

and add colorscheme in .vimrc as:

```
colorscheme atom
```

right now those of us who use vim end up installing this plugins manually on every image. and setting manually a colorscheme in the .vimrc

Regards.

**Comment by moylop260** [comment]
Superseded by https://github.com/Vauxoo/travis2docker/issues/165
