### ISSUE TITLE
Unable to create a new image for a v16.0 project

### ISSUE THREAD

**Issue by hbto** [Vauxoo/travis2docker#195]
When trying to create a new image for projects

git@git.vauxoo.com:vauxoo/somostotem.git in v16.0

and

git@git.vauxoo.com:vauxoo/gandalf.git in v16.0

Two different projects not yet related to one another

They fail with following message:

fatal: unable to access 'https://github.com/Vauxoo/emacs.d.git/': getaddrinfo() thread failed to start

![Screenshot 2023-02-16 at 6 52 48](https://user-images.githubusercontent.com/7598010/219370299-3300e9e6-4920-431b-9a91-d0e95a0f3b0f.png)

Having tried several times. It always fails at the same spot.

In the case of gandalf it does not fail when performing the procedure for v15.0

It seems it is a odoo-version-related issue.

t2d is updated

```
pip install -U travis2docker 
Requirement already up-to-date: travis2docker in /home/hbto/.local/lib/python3.8/site-packages (6.4.8)
Requirement already satisfied, skipping upgrade: Jinja2==3.1.*; python_version >= "3.7" in /home/hbto/.local/lib/python3.8/site-packages (from travis2docker) (3.1.2)
Requirement already satisfied, skipping upgrade: PyYAML==6.0.*; python_version >= "3.7" in /home/hbto/.local/lib/python3.8/site-packages (from travis2docker) (6.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in /home/hbto/.local/lib/python3.8/site-packages (from Jinja2==3.1.*; python_version >= "3.7"->travis2docker) (2.1.1)
```

I am using the switch `--deployv` and `--build-env-args=VIM_INSTALL`

**Comment by luisg123v** [comment]
@rolandojduartem this is the same error message you were getting, isn't it?

**Comment by rolandojduartem** [comment]
@luisg123v, yes, it is. Here the thing is that I could create the image for nortenas 16.0 on Pop!_OS 22.04 LTS 21 hours ago, but when I was creating the same image on Ubuntu 16.04.2 LTS 8 hours ago the process failed showing the same message.

**Comment by moylop260** [comment]
It is related to docker version + ubuntu version in the container (in this case v16.0 use latest ubuntu version)

You need to upgrade your docker (server) installation in order to fix the issue

**Comment by rolandojduartem** [comment]
Hi, @moylop260, I tried to build a image for [kukyflor](https://git.vauxoo.com/vauxoo-dev/kukyflor/-/tree/29f8ee5) and it failed in my computer (no Raditz), the log is [here](https://gist.github.com/rolandojduartem/5e3225fe45a3900f1943974254f157b9). In some point, you can read "fatal: destination path '/home/odoo/.emacs.d' already exists and is not an empty directory.".  In mycomputer is installed:

- travis2docker 6.4.8
- Docker version 23.0.1, build a5ee5b1
- OS Pop!_OS 22.04 LTS

**Comment by moylop260** [comment]
Notice this issue is not related with t2d

You can reproduce the same error using only docker and the quay.io image generated before

For the Humberto example it could be:

`docker run -it --rm quay.io/vauxoo/nocustomers:gandalf-16.0-cc1917b git clone --depth 1 -b master https://github.com/Vauxoo/emacs.d.git /home/odoo/.emacs.d`

The output from my local is the following:

 - <img width="1007" alt="Screenshot 2023-02-20 at 10 49 20" src="https://user-images.githubusercontent.com/6644187/220163278-6b54c30e-8ee0-4a03-a037-6eaf199b90e7.png">

If you run the same command and you have reproduced the error you need to fix your docker server environment itself

**Comment by moylop260** [comment]
I found the issue related: https://github.com/moby/moby/issues/42680#issue-953683711

Notice the docker version must be > 20.10.7

**Comment by hbto** [comment]
@moylop260 I will try your recommendations and will let you know in about two hours from now.

Regards.

**Comment by hbto** [comment]
Thanks a lot guys, 

Using https://docs.docker.com/engine/install/ubuntu/#installation-methods

I was able to fix the problem.

I have upgraded my version of docker from:
![Screenshot 2023-02-20 at 13 00 08](https://user-images.githubusercontent.com/7598010/220184029-a42a51c9-4ec2-456f-a1d7-b89c3169e4a0.png)

to:

![Screenshot 2023-02-20 at 13 14 36](https://user-images.githubusercontent.com/7598010/220184049-3db2d22d-aa0a-48cb-8b49-4456253bf54d.png)
