### ISSUE TITLE
SSH access is not being granted to the local user

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/travis2docker#211]
If I create a new container and try to access using SSH, I'm asked for the odoo user's password.

I checked the file `/home/odoo/.ssh/authorized_keys` and it's empty.

**Comment by antonag32** [comment]
So I looked around, tried different things, and ended up noticing that the .ssh folder is marked as a volume, which explains why authorized keys is not being persisted, apparently copied files do stay the same as they were originally.

This makes me wonder if therefore this feature has ever worked? I think the best solution would be to remove the volume from the base dockerfile (found in DeploV Static repo) but I have created a PR that fixes it in a different way.
