### ISSUE TITLE
[IMP] add version argument to command line.

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/travis2docker#23]
travis2docker commnad line has an option to show currenclty travis2docker version installed.

**Comment by moylop260** [comment]
Currently the command version is not present.
We are using pip features, could you try with follow command:
`pip freeze | grep travis2docker`

**Comment by zaoral** [comment]
@moylop260  I Got it. Thank you Moy.
Maybe we can add this information about how to know the travis2docker version installed in the README file. And we close this issue.

Are you agree?

**Comment by zaoral** [comment]
@moylop260 also this could be helpfull for have the version of the program http://stackoverflow.com/questions/15405636/pythons-argparse-to-show-programs-version-with-prog-and-version-string-formatt
