### ISSUE TITLE
Use CDPATH environment variable

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/travis2docker#50]
### What is `CDPATH`?

> see [here](http://linuxg.net/how-to-set-and-use-the-cdpath-variable/)

I have been using it for a while and I think It should be useful to include into CDPATH the following directories mostly used to move between them:
- `~/` : because Project's dependencies are located here
- Main build directory (e.g. `/root/build/Vauxoo/`)

**Comment by moylop260** [comment]
:+1:

**Comment by moylop260** [comment]
Currently we can use
`cd ~/`
`cd $TRAVIS_BUILD_DIR`

Feel free of re-open or create a PR with this feature if is required yet.

**Comment by osvalr** [comment]
@moylop260 thank you
