### ISSUE TITLE
Use github's webhooks to trigger docker builds on hub.docker.com

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/travis2docker#51]
I really don't know if this issue belongs here, but as this is the tool that generates docker containers for each of our projects, i guess it's the best place.

**Proposal:**

Use the webhooks from github to trigger a new build of a docker image hosted in hub.docker.com, each time a dependency of that image is updated with a commit (or merge) in the main branch (currently 8.0).

For example, lets say, our "very_profitable_client" image has the following odoo dependencies:
- addons-vauxoo
- odoo-ifrs
- odoo-afrs

And, let's say, "odoo-ifrs" gets updated with a new merge. This would trigger an inmediate build on hub.docker.com, which will result in an up-to-date image that then developers would only have to do `docker pull vauxoo/very_profitable_client`.

**What would be needed?**

Each of our client images should be uploaded to hub.docker.com (there are paid plans if we want to keep them private). And then each dependency component should be configured on github to trigger the images that depend on them.

What do you think?
@moylop260 @zaoral @nhomar @ruiztulio @osvalr

**Comment by nhomar** [comment]
On Mon, Apr 18, 2016 at 2:20 PM, Luis Alejandro Martínez Faneyth <
notifications@github.com> wrote:

> Each of our client images should be uploaded to hub.docker.com (there are
> paid plans if we want to keep them private). And then each dependency
> component should be configured on github to trigger the images that depend
> on them.
>
>
We have it already in quay.io with private plans, we can create the
developers version there also.


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by LuisAlejandro** [comment]
And quay.io accepts triggered builds?

**Comment by nhomar** [comment]
Yes.

On Mon, Apr 18, 2016 at 2:29 PM, Luis Alejandro Martínez Faneyth <
notifications@github.com> wrote:

> And quay.io accepts triggered builds?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Vauxoo/travis2docker/issues/51#issuecomment-211541768>
>



-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by moylop260** [comment]
This is unrelated for this project
