### ISSUE TITLE
Install on fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/travis2docker#52]
I've installed with `pip install git+https://github.com/Vauxoo/travis2docker.git` in a Ubuntu 16.04 amd64 (I've check `python2.7` and `python-pip` packages are installed on my system) so when trying to use it there is no command found, is there something am I missing?

### Please see the following asciinema

[![](https://asciinema.org/a/ccn9ftgq7fqxcgwj7epu7miuk.png)](https://asciinema.org/a/ccn9ftgq7fqxcgwj7epu7miuk)

### Expected behavior
```bash
~ ❯  which travisfile2dockerfile
/usr/local/bin/travisfile2dockerfile
~ ❯   
```

**Comment by osvalr** [comment]
A temporal solution for this:
```
$ sudo ln -sf ~/.local/bin/travisfile2dockerfile /usr/local/bin/travisfile2dockerfile
```

**Comment by moylop260** [comment]
I can't to reproduce it in docker ubuntu:16.04

**Comment by moylop260** [comment]
Other temporal solution is add your local bin path to your `PATH`

`export PATH=${PATH}:${HOME}/.local/bin`

The main issue is pip, that all packages is installing in your local path.

**Comment by nhomar** [comment]
On Wed, May 4, 2016 at 8:52 AM, Osval Reyes <notifications@github.com>
wrote:

> $ sudo ln -sf ~/.local/bin/travisfile2dockerfile /usr/local/bin/travisfile2dockerfile
>
>
Lo correcto es cuando instalas en .local es agregarlo a tus path en el
.bashrc.

Los enlaces simbólicos no son buenos por que estás rompiendo lo que pediste
hacer al instalar con --user


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by osvalr** [comment]
@nhomar the normal behavior should be when it's installed all commands related to the package working without any extra step... BTW, I didn't use `--user`

**Comment by nhomar** [comment]
On Wed, May 4, 2016 at 3:40 PM, Osval Reyes <notifications@github.com>
wrote:

> @nhomar <https://github.com/nhomar> the normal behavior should be when
> it's installed all commands related to the package working without any
> extra step... BTW, I didn't use --user
>
>
If it installed on .local either or did you use --user or you did not use
sudo or the pip config is not properlly setted.


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by nhomar** [comment]
On Wed, May 4, 2016 at 8:35 AM, Osval Reyes <notifications@github.com>
wrote:

> I've installed with pip install git+
> https://github.com/Vauxoo/travis2docker.git in a Ubuntu 16.04 amd64 (I've
> check python2.7 and python-pip packages are installed on my system) so
> when trying to use it there is no command found, is there something am I
> missing?
>

CAn you share the outpu tof your PYTHONPATH.


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942
