### ISSUE TITLE
Can't open /etc/init.d/xvfb

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/travis2docker#72]
Summary
-------------

I'm trying to run a travis2docker to [Vauxoo/abastotal](https://github.com/Vauxoo/abastotal)
`t2dvx git@github.com:Vauxoo/abastotal.git 9.0`

![pantallazo-2016-09-19 12-27-22](https://cloud.githubusercontent.com/assets/5335402/18642563/b9cd2c48-7e66-11e6-9c65-0bbdef897f2c.png)

Additional Info
-------------------
- travis2docker **Version: 3.0.7**:

- t2dvx alias
`alias t2dvx="travisfile2dockerfile --root-path=${HOME}/.t2d --run-extra-args='-it --entrypoint=bash -e LANG=en_US.UTF-8 -p 2400-2449:8069 -p 2400-2449:22 -p 2400-2449:5432 -e START_SSH=1 -m 8g --device-write-bps=/dev/sda:10mb --device-read-bps=/dev/sda:10mb --device-write-bps=/dev/md2:10mb --device-read-bps=/dev/md2:10mb --device-write-bps=/dev/sdb:10mb --device-read-bps=/dev/sdb:10mb' --add-remote=vauxoo,vauxoo-dev"`

**Comment by moylop260** [comment]
Thanks for reporting

FYI fixed here:
https://github.com/Vauxoo/docker-odoo-image/pull/155

After finish [the last hub.docker build](https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/bsjyurz2qvbkcf7d8l6ttlm/) you'll need execute: `docker pull odoo-80-image-shippable-auto` to fix it locally.

Other way is use a previous version of travis2docker where the section of `before install` is not considered. By example: `pip install -U travis2docker==3.0.6`
