### ISSUE TITLE
Add command support - `rvm`

### ISSUE THREAD

**Issue by lasley** [Vauxoo/travis2docker#74]
In OCA/website#284 I had to add `bootstrap-sass` and `compass` to dependencies as Ruby gems. Neither of these support the standard Ruby version (anything below 2), so I also had to use the `rvm` command to upgrade to latest ruby in the before_install:

```
before_install:
  - rvm install ruby --latest
  - gem install bootstrap-sass
  - gem install compass --pre
```

[Runbot logs](https://runbot.odoo-community.org/runbot/static/build/3272496-284-982398/logs/job_10_test_base.txt) show that this is not possible though unfortunately:

```
 ---> Running in 86e0aaa78d91
[91m/before_install: line 7: rvm: command not found
```

**Comment by lasley** [comment]
Thinking about this very very hard, this is an issue with the Docker base image right?

**Comment by moylop260** [comment]
Could you try install the binary from https://github.com/Vauxoo/docker-odoo-image/tree/master/odoo-shippable?

**Comment by lasley** [comment]
Sweet so it is in the image and not here. Sorry for opening the ticket in the wrong repo 😦 

I'll submit a PR to the base image after lunch

**Comment by moylop260** [comment]
Thanks man!

NOTE: You can test if is working using the `travisfile2dockerfile --docker-image CUSTOM_IMAGE` after a `docker build --no-cache -t CUSTOM_IMAGE .` from `odoo-shippable` folder
