### ISSUE TITLE
Made avalible docker service if travis services:   - docke setted

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/travis2docker#83]
DRAFT ISSUE
If the travis conf file
![image](https://cloud.githubusercontent.com/assets/10233975/21732756/a7c04868-d420-11e6-8ef9-4a2ad7e36863.png)

https://github.com/Vauxoo/runbot-addons/blob/9.0/.travis.yml#L21-L22

Then add next lines to Docker file generated
https://forums.docker.com/t/how-can-i-run-docker-command-inside-a-docker-container/337/6
VOLUME ["/var/run/docker.sock"]
RUN apt-get -yqq install docker.io

**Comment by hugho-ad** [comment]
@moylop260 Is this feature viable?

What do you  think?

**Comment by moylop260** [comment]
If this feature is working or fixing something then create the change.
