### ISSUE TITLE
error when trying to run travis2docker travis-ci-apt-source-whitelist/ubuntu.json

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/travis2docker#85]
My version is travisfile2dockerfile 3.0.13
I just run t2d git@github.com:Vauxoo/yoytec.git 8.0 

```sh
cmd git --git-dir=/home/kathy/vx/t2d/repo/git_github.com_Vauxoo_yoytec.git config user.name
Traceback (most recent call last):
  File "/usr/local/bin/travisfile2dockerfile", line 9, in <module>
    load_entry_point('travis2docker==3.0.13', 'console_scripts', 'travisfile2dockerfile')()
  File "/usr/local/lib/python2.7/dist-packages/travis2docker-3.0.13-py2.7.egg/travis2docker/cli.py", line 205, in main
    copy_paths=[(expanduser("~/.ssh"), "$HOME/.ssh")] + rcfiles,
  File "/usr/local/lib/python2.7/dist-packages/travis2docker-3.0.13-py2.7.egg/travis2docker/travis2docker.py", line 102, in __init__
    open(os.path.join(travis_ci_apt_src, "ubuntu.json")))
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/travis2docker-3.0.13-py2.7.egg/travis2docker/travis-ci-apt-source-whitelist/ubuntu.json'

```

This happens when I try to load a abastotal customer t2d containter.

**Comment by zaoral** [comment]
@moylop260 
Can you help me with this issue?

**Comment by moylop260** [comment]
The folder `travis-ci-apt-source-whitelist` is a git submodule from https://github.com/Vauxoo/travis2docker/tree/master/src/travis2docker
If you download manually the repository try use `--recursive` git parameter to download submodules.
Or you could try installing from pypi
https://pypi.python.org/pypi/travis2docker

Feel free of re-open this isssue if is not your case
