### ISSUE TITLE
Compiled Binaries

### ISSUE THREAD

**Issue by blaggacao** [Vauxoo/travis2docker#9]
For it to be used as an entry point for new OCA user, we would need pre-build binaries for windows, mac and linux. How can we do this? In go, this would be very simple, however in python no idea...

**Comment by blaggacao** [comment]
@moylop260 I'm thinking loud following our latest and very interesting conversation...

In order to simplify things and be not dependent on a python stack, but manage simple precompiled binaries, I think it would be beneficial to achieve the following:

- Make an appropriate Docker Base image for OCA repos.
- Adapt the travis files to work with docker.
- Run you travis2docker on the repos as a maintenence task (can be automatized)

So each repo count's with a DEV docker file...

Work otherwise with standard docker tooling... binaries available, everything hardened and multi-platform...

I see no more elegant way to achieve what we are aiming for...
What do you think about this idea?

**Comment by moylop260** [comment]
FYI We will follow this issue in following https://github.com/OCA/maintainer-quality-tools/pull/303
