### ISSUE TITLE
[IMP] Set automatically the enviroment variable TRAVIS_PULL_REQUEST and TRAVIS_PULL_REQUEST_BRANCH

### ISSUE THREAD

**Issue by JesusZapata** [Vauxoo/travis2docker#97]
When run `travisfile2dockerfile git@github.com:Vauxoo/runbot-addons.git pull/93` and before to run the `10-build.sh` and `20-run.sh`

We run the entrypoint `/entrypoint.sh` always show all check in green because the enviroment variable `TRAVIS_PULL_REQUEST` and `TRAVIS_PULL_REQUEST_BRANCH` is not set

@moylop260 
What do you think about this issue?

**Comment by moylop260** [comment]
Note: We will need to consider this case for GITLAB too
